### PR TITLE
Bugfix  build issues

### PR DESCRIPTION
**Pull request by taybin**
This fixes a number of build errors and deprecation warnings.

### CODE REVIEW

**Comment by taybin** [comment]
Fixes issue https://github.com/node-influx/node-influx/issues/352

**Comment by taybin** [comment]
This will help unblock the other PRs which are failing.

**Comment by bencevans** [comment]
Thanks for your work @taybin. Eager to get Travis happy again too. Have you made any further headway? 
 I plan to work on the same goal.

**Comment by taybin** [comment]
@bencevans I don't have any pending changes.  Feel free to work off of my branch to get a headstart on the remaining changes, if you like.

**Comment by bencevans** [comment]
Thanks for your PR @taybin. I got carried away on my own branch and updated all the dependencies etc too in #354.

**Comment by taybin** [comment]
I'm fine with that.  I just wanted the build fixed so I could work on adding UDP support.  Thanks!

**Comment by bencevans** [comment]
Awesome. Looking forward to it :smile_cat:  :rocket:

**Pull request closed without merging**
