### PR TITLE
Return errors (such as ECONNREFUSED) when you're out of hosts

### PR DESCRIPTION
**Pull request by joel-airspring**
If you make a request against a non-existent hostname, you get a nice error, with code ENOTFOUND.

But if you make a request against a server that does not have influxdb running, you don't get an ECONNREFUSED.   This is because a resubmit attempt hides the specific error, giving only 'No hosts available'.

Since some specific error codes are hidden, it makes it impossible to distinguish between, for example, ECONNREFUSED and ETIMEOUT

This is based of 3.4.0, since that's the version I'm using.

### CODE REVIEW

**Comment by nichdiekuh** [comment]
I see your point and it makes sense to return a proper error message instead of the "no host available" message. Have you considered upgrading to 4.x and fixing the conflict? ;)

**Comment by joel-airspring** [comment]
I'm stuck at 3.4 in our IT environment because we use influx 0.8, so I need this fixed in 3.4.0.

However, I can redo in master if that would help you.

**Comment by joel-airspring** [comment]
Thanks for merging #98!  Can this PR be merged into 3.4.x?

**Comment by bencevans** [comment]
Thanks for the pull-request @joel-airspring, this has been merged into the 3.x branch and released on npm in `3.5.0` :+1:

**Pull request closed without merging**
