### PR TITLE
Prevent crash when body is not defined.

### PR DESCRIPTION
**Pull request by EricSmekens**
#103 See issue.

Any feedback is welcome on this change. Different solution as well, because for me it is not clear why body is undefined.

### CODE REVIEW

**Comment by bencevans** [comment]
Thanks for opening this pull-request. Please could you fix the tests before we can merge.

**Comment by EricSmekens** [comment]
Changed the way the error is handled. Change has less impact now, as I was not aware what the possible output of body could be.

You want me to rebase it?

**Comment by bencevans** [comment]
Not to worry about rebasing, I'm happy with just merging.

Before I merge into master we need to add test coverage and fix the lint error. If you're able to add these too it'd be much appreciated!

**Comment by EricSmekens** [comment]
Which lint error? Sorry for the questions, but I'm a bit lost at this moment in the library and also the output of Travis confuses me atm.

**Comment by bencevans** [comment]
Not to worry! It's saying there's some whitespace at the end of line 78, if you could remove the spaces at the end of the line it'll fix it :smile_cat:

**Comment by bencevans** [comment]
Don't worry about the changes. I did it on merge. Thanks for the patch :+1:

**Comment by EricSmekens** [comment]
Thank you!

**Pull request merged**
