### PR TITLE
Support InfluxDb 0.12

### PR DESCRIPTION
**Pull request by leorossi**
Basically I refactored a little the test suite to make tests runnable independently.
Also the test db is created and deleted afetr every run. 
Few changes on library, to match some new behavior of the library.

I tested it locally with InfluxDb `0.12.1`, the only missing test is the `#query failover` that I don't understand completely. But happy to learn and fix also that!

Refs: #122

### CODE REVIEW

**Comment by eliperelman** [comment]
Still need something like https://github.com/node-influx/node-influx/pull/92 for full support.

**Comment by connor4312** [comment]
Hi @leorossi, thanks for the contribution! A few couple to make before merging this:

 - Update tests to use ES5; the current version of Influx supports Node 0.12, and though we're dropping support for lower versions in 5.0.0 that's not ready to release yet.
 - Ensure edge cases are handled in the getSeries function; for instance, running `SHOW SERIES` on an empty database returns `{"results":[{}]}`, which will cause your code to throw an error

Thanks again!

**Comment by simison** [comment]
Any changes getting back to this @leorossi ? :-) Great job so far!

**Comment by leorossi** [comment]
hei @simison it's been a few weeks I am not working anymore with InfluxDB, I fixed the issues pointed out by @connor4312 but I am spending some time rebasing onto the most recent `master`, hope to have some updates from you very soon!

**Comment by MarkHerhold** [comment]
Hey @leorossi, can I ask what you are using now in place of InfluxDB, or have you just moved on to a different portion or new project?

**Comment by leorossi** [comment]
@MarkHerhold I changed my job and we are not using InfluxDB, but plan is to bring that on board so I would probably work again on this library in the next few weeks!

**Comment by Apollon77** [comment]
... and we have InfluxDB 1.0 now :-) is there more needed?

**Comment by connor4312** [comment]
Thanks for all the work here! Moving forward I want to target Influx 1.0 in node-influx 5.0.0. I'll close this PR for now but may end up borrowing some things as applicable :)

**Pull request closed without merging**
