### PR TITLE
fix: prevent sql injection #486

### LINKED ISSUE #486: Bad string generating by Expression
## Expected Behavior

Trying to escape some random input to break expression
```
exp = new Influx.Expression();
exp.tag('symbol').equals.value(`GAZP()\'`).toString() // **`"symbol" = 'GAZP()\\\''`**
```
And it should escape characters correctly

## Actual Behavior
But it doesn't escape them
```
exp = new Influx.Expression();
exp.tag('symbol').equals.value(`GAZP()\'`).toString() // **`"symbol" = 'GAZP()\\''`**
```

## Steps/Code to Reproduce the Problem
```
const influx = require('influx')
const exp = new influx.Expression();
exp.tag('symbol').equals.value(`GAZP()\'`).toString()
// ...
```

## Specifications

  - Version: 5.5.1
  - Platform: Darwin

### PR DESCRIPTION
**Pull request by robertsLando**
- Fixes #486 
- Bumped deps
- Audit fix

## Checklist

- [x] A test has been added if appropriate
- [x] `npm test` completes successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)

### CODE REVIEW

**Comment by robertsLando** [comment]
@bencevans

**Comment by bencevans** [comment]
Thanks for delving into this @robertsLando. Please could you update the tests accordingly?

**Comment by robertsLando** [comment]
@bencevans I have, but if you see the ci fails with a strange error that is not happening on my instance. Could you help?

**Comment by bencevans** [comment]
:thinking: hmm yes, I've just pulled down. Shall investigate later on :+1:

**Comment by robertsLando** [comment]
@bencevans Let me know :)

**Comment by robertsLando** [comment]
@bencevans Seems ok now :tada:

**Comment by svedbg** [comment]
This PR broke linting of the filex in master. Prettier was not used and now tests are not passing! Also there is regression in the code: https://github.com/node-influx/node-influx/issues/516

**Pull request merged**
