### PR TITLE
Fix #274 Continuous typo

### LINKED ISSUE #274: Typo: "continous" -> "continuous"
Sometimes the word "continuous" is being spelled incorrectly as "continous", including `showContinousQueries` method, which should be `showContinuousQueries`

### PR DESCRIPTION
**Pull request by adrianliaw**
Fixing #274: Correcting the spelling of the word "continuous"

### CODE REVIEW

**Comment by connor4312** [comment]
Thanks for the PR! Unfortunately as-is this will be a breaking change. Can you add a method with the old name that 'proxies' to the fixed name?

**Comment by adrianliaw** [comment]
@connor4312 Thanks for the quick reply! One thing I want to make sure is that, should the original method considered as a "deprecated" method? i.e. should I proxy the old method name to the new one, and then label it as a deprecated method (inside documentation)?


Also, during using this function, I've found out the same issue as in #270, which is that `showContinuousQueries` shouldn't have a `database` argument, since we just cannot specify database when running `show continuous queries` inside influx, and specifying database does nothing.  
I think it's a good idea to remove the argument from the method, however it'll also become a breaking change. If you think this change is appropriate, how about keeping the original `showContinousQueries` (label as deprecated) and have the new `showContinuousQueries` method takes no arguments?

**Comment by connor4312** [comment]
Yes, the original method would be considered deprecated.

That proposal for `showContinuousQueries` sounds like a good one!

**Comment by adrianliaw** [comment]
Closing this in favour of #282

**Pull request closed without merging**
