### PR TITLE
.queryRaw takes only one query

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by connor4312** [comment]
I admit I have have not tested it, but in theory you should be able to pass multiple semicolon-delimited queries into queryRaw. Is this not the case?

**Comment by dandv** [comment]
I haven't tried semicolon-delimited queries, assuming the call convention was the same as for `.query()` - an array of Strings.

**Comment by connor4312** [comment]
I'll update this I think; queryRaw is meant to be a lower-level access but there's no reason we can't do a quick `.join(';')` in there.

**Comment by connor4312** [comment]
I've gone ahead and updated queryRaw to accept multiple queries, as the original docstring indicates. But, thanks for the PR, as always!

**Pull request closed without merging**
