### PR TITLE
Add TypeScript Definition

### PR DESCRIPTION
**Pull request by SPARTAN563**
This PR adds a TypeScript definition file which will be automatically detected for TypeScript 1.7+ (thanks to its `node` module resolution policy). It should greatly simplify integration into TypeScript projects as well as make navigating the codebase easier for tools which support TypeScript definition files for JavaScript.

### CODE REVIEW

**Comment by bencevans** [comment]
Hi @SPARTAN563 

I only have very limited TypeScript experience and don't think I can commit to keeping this up to date as I don't currently make use of it.

Is there a way these definitions can be maintained separately to the main project repo or is it a necessity that it lives in the same repo?

Kind regards

Ben

**Comment by SPARTAN563** [comment]
Hi Ben,
It is possible to maintain them in a separate repo, DefinitelyTyped being
the traditional one, however with the ecosystem going through a state of
flux (and with the confusion that finding the definitions outside of the
project induces) I'd recommend at least trying to keep them here.

With the understanding that you don't have the need or familiarity to
maintain the definition, can I ask that you allow me to help out there?
It's something I make use of and will continue to do so, only breaking API
changes should require updates to it, and iterative API changes can be
added as people have a need to use them. Does that work for you?

Kind regards,
Benjamin

**Comment by bencevans** [comment]
If you're happy to maintain, it would be very much appreciated! I'll add you onto the push list... :)

**Comment by SPARTAN563** [comment]
Thanks Ben, if you could also just let me know (open an issue and assign it
to me) whenever there's a major change which you'd like me to update the
definition for - I'll make sure to get back to you with the new one ASAP.

**Comment by bencevans** [comment]
Okay, shall try and remember. Is there a way of testing on the CI if the
definitions no longer match the codebase that we can run each time to be sure?

On Apr 23 2016, at 5:40 pm, Benjamin Pannell &lt;notifications@github.com&gt;
wrote:  

> Thanks Ben, if you could also just let me know (open an issue and assign it  
to me) whenever there's a major change which you'd like me to update the  
definition for - I'll make sure to get back to you with the new one ASAP.  
  
On Sat, 23 Apr 2016, 18:33 Ben Evans &lt;notifications@github.com&gt; wrote:  
  
&gt; Merged #129 &lt;https://github.com/node-influx/node-influx/pull/129&gt;.  
&gt;  
&gt; —  
&gt; You are receiving this because you were mentioned.  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/node-influx/node-
influx/pull/129#event-638684494&gt;  
&gt;  

>

> —  
You are receiving this because you modified the open/close state.  
Reply to this email directly or [view it on GitHub](https://github.com/node-
influx/node-influx/pull/129#issuecomment-213777360)

**Comment by SPARTAN563** [comment]
I'll look into it tomorrow, unfortunately I don't think it's particularly
straight forward unless the library is written in typescript as well

**Pull request merged**
