### PR TITLE
write-point: Fix cannot read database property error when missing options

### PR DESCRIPTION
**Pull request by bencevans**
#134

### CODE REVIEW

**Comment by connor4312** [comment]
I think a better general-purpose case would be something like this:

```
function resolveOptCallback(options, callback) {
  if (typeof options === 'function') {
    callback = options
    options = {}
  }

  return {
    callback: callback || _.noop
    options: options || {},
  }
}
```

This satisfies all of the cases of:
 - neither the callback nor options being given
 - callback being given in place of options
 - options given without callback
 - options not given but callback given
 - both callback and options given

**Comment by bencevans** [comment]
Looks good. Wanna drop it in?

**Comment by SPARTAN563** [comment]
@connor4312 - when you add that, it may also be worth adding it to the `writePoint` and `writePoints` methods (in addition to the `writeSeries` method currently covered by this PR).

Also, would it be possible to rebase this on `master` so I can open a PR from [here](https://github.com/SierraSoftworks/node-influx/tree/fix-write-point-missing-options-definition) with the updated TypeScript definitions?

**Comment by connor4312** [comment]
@bencevans: I've added this in 575e27b
@SPARTAN563: done 😄  we can get this updated when it's ready to merge

**Comment by SPARTAN563** [comment]
Looks good to me, though looks like it's a couple of commits behind master - I'll keep an eye on this and open the PR as soon as I'm able to :+1:

**Comment by SPARTAN563** [comment]
Have just quickly rebased this on the latest master and double checked the definition changes. Going to merge this as per the request in #141

**Pull request merged**
