### PR TITLE
fix get wrong http request body length

### PR DESCRIPTION
**Pull request by peaksnail**
In fact, the length of string in node may not be equal the actual string length, and the server will get wrong sql,so use Buffer to get the string length.

example:

var text='你好' // this string is chinese
console.log(text.length) will be 2,but actual it's  6.

### CODE REVIEW

**Comment by connor4312** [comment]
Good catch! Do you mind adding a quick test case for this?

**Comment by brokentone** [comment]
I'm just learning InfluxDB and got caught by this bug which wasted about 6 of my hours debugging in the last 2 days. Looks like it was fix 2 years ago, but never released. It was kind of a lark that I even found it... but that's a different story.

Any chance we could get a new release? @bencevans @connor4312

**Comment by bencevans** [comment]
Sorry to hear that @brokentone we'll get something up shortly.

**Comment by brokentone** [comment]
@bencevans ehh, it's free software, I can't be too upset. Appreciate the quick response and looking forward to the release!

**Pull request merged**
