### PR TITLE
Add TypeScript Definition Tests

### PR DESCRIPTION
**Pull request by SPARTAN563**
This PR adds some small tests to help ensure we ship a valid definition file, primarily around compiling it and a very basic usecase (taken from the examples folder).

I've also rewritten the definition file to better support the `node` module resolution mode in TypeScript - it was previously targetting what is known as "ambient" or "global" inclusion, something which is being phased out as the compiler becomes more capable of resolving the correct definitions for various modules.

### CODE REVIEW

**Comment by bencevans** [comment]
I shall take your expertise as signoff on this one. Automatic tests are awesome though, nice addition!

Not sure if https://github.com/node-influx/node-influx/pull/135 will affect the TypeScript definitions. If you'd like to review and merge that one when you're happy that'd be awesome :)

**Comment by SPARTAN563** [comment]
Thanks, will take a look at #135 to make sure there aren't any changes necessary as soon as I land.

**Comment by SPARTAN563** [comment]
Unfortunately struggling to action the changes via the website, I'll need to do so on Tuesday when I'm back in front of a computer (unless you would like to do so). Apologies

**Comment by bencevans** [comment]
No worries, whenever suits :)

**Pull request merged**
