### PR TITLE
Simple README update

### PR DESCRIPTION
**Pull request by shaunwarman**

### CODE REVIEW

**Comment by bencevans** [comment]
May I enquire as to why you closed this @shaunwarman.

LGTM

**Comment by shaunwarman** [comment]
Ah sorry, I noticed this throughout the entire README. So I figured a change throughout would probably make more sense.

**Comment by shaunwarman** [comment]
Maybe just 2 places now that I look again :)

**Comment by bencevans** [comment]
I think the idea was to show that the comma was optional dependent on the arg.

I'm happy to switch though if it's what's more common/people are used to!

**Comment by bencevans** [comment]
Spotted 8 in current master's README

**Comment by shaunwarman** [comment]
Updated, completely up to you on the change.

**Comment by bencevans** [comment]
From what I recall, this seems more in line with other projects. Cheers @shaunwarman

**Pull request merged**
