### PR TITLE
method for adding schema definition in runtime

### PR DESCRIPTION
**Pull request by flafik**
issue [#310](https://github.com/node-influx/node-influx/issues/310)

### CODE REVIEW

**Comment by lerit** [comment]
@flafik  can you please resolve the conflict?
this pull very useful for me ,thanks!

**Comment by flafik** [comment]
Hello @lerit ,
I've tried to resolve the conflict, however there are some build errors originating in previous commits, if I checked it correctly. So I am not able to pass the checks. Hopefully those issues will be resolved.

**Comment by lerit** [comment]
@flafik thank you for the efforts.
i suggest make a new pull request,because It's been a long time since this pull request,and maybe some strict limit by typescript cause the failed.

**Comment by bencevans** [comment]
There's now a new version of npm released and we've since worked to get the development dependencies updates, code style sorted and tests all well on Travis. We would love to include your update but please could it be resubmitted as a pull-request with commit messages in [semantic format](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) ontop of the most recent master.

**Pull request closed without merging**
